# Generated by Django 5.1 on 2024-08-25 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0004_book_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
    ]
