# Generated by Django 5.1 on 2024-08-25 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0006_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='promptDescription',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='ImagePrompt',
        ),
    ]
