# Generated by Django 5.1 on 2024-09-06 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblio', '0008_pod'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pod',
        ),
    ]
